version: '3'

services:
  app:
    image: 12evgen/topfashion-backend:latest
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST:mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=changeme!
      - WORDPRESS_DB_NAME=wordpress
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${PROJECT_BASE_URL}`)"
      - traefik.docker.network=proxy_webgateway
    volumes:
      - app:/var/www/html
    networks:
      - web
      - backend
    links:
      - mysql

  mysql:
    image: mariadb
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    environment:
      - MYSQL_ROOT_PASSWORD=changeme!
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=changeme!
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"
    networks:
      - web
      - backend

networks:
  web:
    external:
      name: proxy_webgateway
  backend:
    driver: bridge

volumes:
  app:
  mysql: