version: '3'

services:
  wordpress:
    image: 12evgen/topfashion-backend:latest
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST:mysql:3306
      - WORDPRESS_DB_USER=$DB_USER
      - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
      - WORDPRESS_DB_NAME=$DB_NAME
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${PROJECT_BASE_URL}`)"
      - traefik.docker.network=proxy_webgateway
    volumes:
      - wordpress:/var/www/html
    networks:
      - web
      - backend
    links:
      - mysql

  mysql:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
    labels:
      - traefik.docker.network=proxy_webgateway
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - web
      - backend

networks:
  web:
    external:
      name: proxy_webgateway
  backend:
    driver: bridge

volumes:
  wordpress:
  mysql: